Fix Circle CI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -50,7 +50,13 @@ jobs:
           command: |
             set -e # Any failure is a failure
             . venv/bin/activate
-            python3 src/main.py doctor --verbose
+            # First failure is expected
+            if python src/main.py doctor; then
+              exit 1  # This command should have failed
+            else
+              exit 0  # This command failure is expected
+            fi
+            # Success case test for this in "Test install basic package"
 
       - run:
           name: Test list api versions
@@ -89,6 +95,8 @@ jobs:
             set -e # Any failure is a failure
             . venv/bin/activate
             python3 src/main.py install basic packages -v
+            # Now, doctor should work
+            python3 src/main.py doctor
 
       - run:
           name: Test list others
