Install jdk_switcher in CircleCI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,7 +5,7 @@
 version: 2
 
 jobs:
-  build:
+  build-jdk8:
     docker:
       # Specify service dependencies here if necessary
       # CircleCI maintains a library of pre-built images
@@ -16,7 +16,6 @@ jobs:
       # specify the version you desire here
       # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
       - image: circleci/python:3.7.0
-      
 
     working_directory: ~/android-sdk-enhanced-code-checkout-directory
 
@@ -31,7 +30,7 @@ jobs:
           - v1-dependencies-
 
       - run:
-          name: install Python dependencies
+          name: Install Python dependencies
           command: |
             sudo apt-get install python3 python3-pip python3-venv
             # Setup python3
@@ -45,10 +44,69 @@ jobs:
           key: v1-dependencies-{{ checksum "requirements.txt" }}-28
 
       - run:
-          name: Python 3 tests
+          name: Run JDK8 tests
           command: |
             # Any failure is a failure
             set -e
             python3 -m venv venv
             . venv/bin/activate
-            bash ./tests/test_doctor.sh
+            # Verify doctor succeeds
+            python src/main.py doctor --verbose
+
+  build-jdk9:
+    docker:
+      # Specify service dependencies here if necessary
+      # CircleCI maintains a library of pre-built images
+      # documented at https://circleci.com/docs/2.0/circleci-images/
+      - image: circleci/openjdk:10-jdk
+      # specify the version you desire here
+      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
+      - image: circleci/python:3.7.0
+
+    working_directory: ~/android-sdk-enhanced-code-checkout-directory
+
+    steps:
+      - checkout
+
+      # Download and cache dependencies
+      - restore_cache:
+          keys:
+          - v1-dependencies-{{ checksum "requirements.txt" }}-28
+          # fallback to using the latest cache if no exact match is found
+          - v1-dependencies-
+
+      - run:
+          name: Install Python dependencies
+          command: |
+            sudo apt-get install python3 python3-pip python3-venv
+            # Setup python3
+            python3 -m venv venv
+            . venv/bin/activate
+            pip3 install -r requirements.txt
+
+      - save_cache:
+          paths:
+            - ./venv
+          key: v1-dependencies-{{ checksum "requirements.txt" }}-28
+
+      - run:
+          name: Run JDK9 tests
+          command: |
+            # Any failure is a failure
+            set -e
+            python3 -m venv venv
+            . venv/bin/activate
+            # The only thing we want to test with JDK9 is the doctor returns failure
+            if python src/main.py doctor --verbose; then
+              exit 1  # This command should have failed
+            else
+              exit 0  # This command failure is expected
+            fi
+
+# https://discuss.circleci.com/t/how-to-test-multiple-versions-by-triggering-jobs-with-a-shell-function/11305
+workflows:
+  version: 2
+  build:
+    jobs:
+      - build-jdk8
+      - build-jdk9
